## Project configuration
# JIRA Project ID or key
project: TEST
# JIRA Issue type ID or name
issue_type: Bug
# JIRA Issue summary prefix, leave empty if not required
summary_prefix: My Issue Prefix
## Workbench alerts configuration
# Poll time in seconds
poll_time: 15
# Workbench alerts retrieval start time (UTC timezone),
# If empty, defaults to 24 hours before the request is made.
start_time: 1970-01-01 00:00:00
# Workbench alerts retrieval end time (UTC timezone),
# If empty, defaults to the time the request is made.
end_time:
# Skip closed alerts in Vision One, else create a new JIRA and re-open the alert.
skip_closed: true
## Logging configuration
# Enable debug logging
debug: false
# Enable logging to file instead of stdout
to_file: false
# Log filename
filename: app.log
# Log file max size in MB
file_size: 50
# Log files rotation count
file_count: 5

## Credentials configuration
v1:
  # Vision One API URL
  url: https://api.region.xdr.trendmicro.com
  # Vision One API Token
  token: token
jira:
  # JIRA URL
  url: https://company.atlassian.net
  # JIRA Cloud Username (User email address associated to the API Token)
  # Important: leave empty if using JIRA On-premise
  username: email@address.com
  # JIRA Cloud API Token or On-premise Personal Authentication Token
  token: token

## JIRA key to JIRA/Vision One value mapping
fields:
  # field: JIRA field name or key
  # value: JIRA/Vision one value
  - name: Checkbox
    value:
      - 41786
      - 41787
  - name: Dropdown
    value: Option 1
  - name: reporter
    value: email@address.com
  - name: assignee
    value: John Doe
  - name: labels
    value:
      - alert.alert_provider
      - alert.id
  - name: priority
    value: alert.severity
    mapping:
      P3: low
      P2: medium
      P1: high
      P0: critical
  - name: resolution
    value: Unresolved

## JIRA issue status to Vision One Alert investigation status mapping
status:
  # name: JIRA status name
  # inv: Vision One Alert investigation status
  # fields: (Optional) extra fields required to be set during the transition,
  # for example when closing an issue, engineer resolution is required.
  - name: To Do
    inv: New
  - name: In Progress
    inv: In Progress
  - name: Done
    inv: Closed
    fields:
      - name: Score
        value: alert.score